using MovieJournalDTO;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace TMDBGateway.TMDBServices
{
    
    public class TMDBGateWayService
    {
        // The API_Key generated by http://www.themoviedb.org/
        string APIKey = "1396960c122fb1696773a4d42f994866";


        public MovieList GetPopular()
        {
            using (var client = new HttpClient())
            {
                HttpResponseMessage response =
                    client.GetAsync("http://api.themoviedb.org/3/discover/movie?sort_by=popularity.desc&api_key="+APIKey).Result;
                return response.Content.ReadAsAsync<MovieList>().Result;
            }
        }

    }
}
