using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TMDBGateway.TMDBServices
{
    
    public class TMDBGateWayService
    {
        // The API_Key generated by http://www.themoviedb.org/
        string APIKey = "1396960c122fb1696773a4d42f994866";
    }
}
